### PR TITLE
set CROSSCOMPILING_EMULATOR

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Do you really want to support a variable that is sometimes a string, sometimes a boolean?

On the linux code path we have:
```
 33         if [ -f ${CI_SUPPORT}/${CONFIG}.yaml ]; then                                                                                                                                                       
 34             echo "CMAKE_CROSSCOMPILING_EMULATOR: " >> ${CI_SUPPORT}/${CONFIG}.yaml
 35             echo "- /usr/bin/qemu-${HOST_PLATFORM_ARCH}-static"  >> ${CI_SUPPORT}/${CONFIG}.yaml
 36             echo "CROSSCOMPILING_EMULATOR: " >> ${CI_SUPPORT}/${CONFIG}.yaml    
 37             echo "- /usr/bin/qemu-${HOST_PLATFORM_ARCH}-static"  >> ${CI_SUPPORT}/${CONFIG}.yaml
 38         fi 
```

**Comment by isuruf** [comment]
I agree that it's confusing. However, we usually test that it is non-empty on Linux too. CMake use `CMAKE_CROSSCOMPILING_EMULATOR` to launch binaries, but I'm not setting it here because I couldn't think of what to set here. The emulator is called by the OS itself so there's no path for it.

**Comment by hmaarrfk** [comment]
Understood on the non-emptiness front. Is the following suggestion possible:
https://github.com/conda-forge/conda-smithy/pull/1808#discussion_r1405507116

**Review by hmaarrfk — APPROVED** [review]
Good by me, but I haven't tested on windows. merge if you have

**Comment by isuruf** [comment]
This is tested on CI here.

**Pull request merged**
