### PR TITLE
delete libcrypto & libssl from C:\Windows\System32 [master]

### PR DESCRIPTION
**Pull request by h-vetinari**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Same as #84; as [requested](https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/84#issuecomment-619539923)

### CODE REVIEW

**Comment by beckermr** [comment]
I’ll need to rerender with my local version of smithy for this one.

**Comment by h-vetinari** [comment]
> I’ll need to rerender with my local version of smithy for this one.

Yeah, I figured something like that after the rerender in #84 (back when it was pointing to master) broke things even more. ;-)

**Comment by h-vetinari** [comment]
I rebased & squashed the commits together.

**Comment by seanyen** [comment]
@h-vetinari @beckermr Hi! Just wanted to bring this to your attention. I have some recipes which are using `git_url` to get the sources:

```yaml
source:
  - git_url: https://github.com/ros-gbp/actionlib-release.git
    git_rev: release/melodic/actionlib/1.12.0-1
    folder: src/ros-melodic-actionlib
```

And after updating to `conda-forge-ci-setup=3.0.4` and later, the `conda-build` started to fail with the following errors on Windows platform:

```
BUILD START: ['ros-melodic-fat-all-2020.05.15-py36h71cc2b5_0.tar.bz2']
Cloning into bare repository 'D:\bld\git_cache\github.com\ros-gbp\actionlib-release.git'...
Cloning into 'D:\bld\ros_1589607757022\work\src/ros-melodic-actionlib'...
fatal: Could not read from remote repository.
```

After I manually pinned `conda-forge-ci-setup=3.0.3`, the problem is gone.

**Comment by h-vetinari** [comment]
@seanyen 
Sorry to hear that. Could you try adding if openssl (and/or git) to your build environment solves things?

**Comment by beckermr** [comment]
cc @conda-forge/core I have seen this bug too. Any ideas on how to fix? Do we need to add git as a dep to conda-build?

**Comment by isuruf** [comment]
We do have `git` as a dependency. Maybe we are getting `git` from another source.

**Comment by beckermr** [comment]
Hmmmm. I used `where git` in a job and got this

```
C:\Miniconda\Library\bin\git.exe
C:\agents\2.168.2\externals\git\cmd\git.exe
C:\Program Files\Git\bin\git.exe
```

unless the last thing is first, this appears correct.

**Comment by beckermr** [comment]
PR here: https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/94

Is git on windows linked incorrectly?

**Comment by isuruf** [comment]
@senyen, can you check if this is fixed now?

**Comment by seanyen** [comment]
@isuruf I verified `conda-forge-ci-setup v3.0.9` that fixed this problem. Thanks!

**Pull request merged**
