### PR TITLE
unset CPU_COUNT for github actions as well

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

cc @wolfv

### CODE REVIEW

**Comment by wolfv** [comment]
cool! 
I wonder if we really need to set it. I haven't had issues with this on Azure in the robostack builds etc.

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
@jakirkham, yes, we can keep the CPU_COUNT setting for other CI.

@conda-forge/core, any other comments?

**Comment by wolfv** [comment]
looks good to me!

**Comment by mariusvniekerk** [comment]
LGTM

**Pull request merged**
