### PR TITLE
Use m2-git as git on windows is broken

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
Do we need to adjust the conda-build recipe too?

**Comment by isuruf** [comment]
conda-build doesn't pull in `git` right?

**Comment by isuruf** [comment]
Btw, `git` on windows is bundling `m2-` packages which breaks everything.
```
2020-05-16T18:56:31.3786571Z ClobberWarning: This transaction has incompatible packages due to a shared path.
2020-05-16T18:56:31.3787501Z   packages: conda-forge/win-64::git-2.26.2-0, defaults/win-64::m2-msys2-runtime-2.5.0.17080.65c939c-3
2020-05-16T18:56:31.3788232Z   path: 'library/usr/bin/cygcheck.exe'
```

**Comment by ocefpaf** [comment]
Thanks @isuruf!

**Comment by beckermr** [comment]
I thought you said in another comment that it did pull in git. The fact that it doesn't is a bug right? Otherwise our version of conda-build cannot handle git_urls, not that we should be using them.

**Comment by isuruf** [comment]
I did? Sorry. That was a mistake.

**Comment by beckermr** [comment]
No worries. But shouldn't we be adding git to that recipe?

**Comment by isuruf** [comment]
Sure. Want to send a PR? (We also have to add `patch`) If you are doing that we should fix conda-smithy-feedstock too as that pulls in `git` and we would have both `git` and `m2-git`.

**Comment by beckermr** [comment]
I'll send some PRs around.

**Pull request merged**
