### PR TITLE
don't try to copy packages in prod channel

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by beckermr — APPROVED** [review]
I can't see any problems with the logic. Fwiw webservices also doesn't duplicate uploads so any extra copy commands sent there return quickly as success

**Comment by isuruf** [comment]
When there are `arch` and `noarch` outputs in the same recipe, `noarch` output might be uploaded by a different CI, and trying to upload the `noarch` output to `cf-staging`. This PR fixes this issue as well.

**Comment by beckermr** [comment]
Yup that's right! Thanks for fixing!

**Comment by beckermr** [comment]
There is still a race condition when none of the outputs have made it yet.

**Comment by isuruf** [comment]
True, but we've ignored that from the beginning right?

**Comment by beckermr** [comment]
Yup! Just leaving notes for myself on where the problems remain for future me who forgets this entire convo.

**Comment by isuruf** [comment]
Thanks for the review

**Pull request merged**
