### PR TITLE
Add strict priority for pypy builds

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
Ready for a review

**Comment by beckermr** [comment]
We recommend strict priority anyways right? see here: https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge

Should we make this the default everywhere?

**Comment by isuruf** [comment]
There was a PR https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/50. I don't want to add strict globally as that would take time to get consensus.

**Comment by beckermr** [comment]
sounds good. I'd say merge and see what gives, but feel free to wait for others to chime in if they have opinions.

**Comment by isuruf** [comment]
Thaks @beckermr for the review. I'll revert if there are any issues.

**Pull request merged**
