### PR TITLE
Fix upload_global_config not actually opening the file

### PR DESCRIPTION
**Pull request by hmaarrfk**
Fixes https://github.com/conda-forge/conda-smithy/issues/878

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
how did this even build? the build2.0 branch fails with the same error on linux. So it isn't about my PR.

Though that raises the issue, how did I even rerender with this?

**Comment by hmaarrfk** [comment]
@conda-forge/core friendly bump. 

This is really a 1 line change that requires the input of `safe_load` to be a file handle and not a file name.

It would really help me stay in line with conda-forge builds in my own channels (eg. OpenCV linked to above) when I require specific patches to be included ahead of their regular release cycle.

**Comment by jakirkham** [comment]
Looks fine to me. Though I have not really looked at this file, so am soliciting a second review from Marius who basically wrote it.

**Comment by hmaarrfk** [comment]
Of course. Thanks for having a look!

**Comment by hmaarrfk** [comment]
Thanks!

**Pull request merged**
