### PR TITLE
Fix `channel_sources` upload checks

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Instead of checking whether the string starts with the pattern, check for a full match.

cc/ @isuruf @beckermr

### CODE REVIEW

**Comment by beckermr** [comment]
@jaimergp shall we merge this?

**Comment by jaimergp** [comment]
If there are no comments, I guess!

**Comment by beckermr** [comment]
We need to bump the version of the ci-setup package here too. Then we can merge!

**Comment by beckermr** [comment]
Thank you!

**Pull request merged**
