### PR TITLE
MNT: rerender

### LINKED ISSUE #187: @conda-forge-admin rerender
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #187.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #187

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by beckermr** [comment]
I am closing this one. Will open a new PR with the changes above once smithy is fixed:

https://github.com/conda-forge/conda-smithy/issues/1593

**Comment by beckermr** [comment]
@kkraus14 @jakirkham any ideas why the cuda migrators are here? I think it'd be easier to put cuda in build and ignore the run exports maybe?

**Comment by isuruf** [comment]
yeah, add it to build and ignore_run_exports_from is better.

**Pull request closed without merging**
