### PR TITLE
check if toolchain_x in list

### PR DESCRIPTION
**Pull request by CJ-Wright**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by scopatz** [comment]
not sure why CI is failing.

**Comment by scopatz** [comment]
```
+ ff_ci_pr_build --help
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/conda-forge-ci-setup_1534958874189/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/ff_ci_pr_build", line 7, in <module>
    from conda_forge_ci_setup.ff_ci_pr_build import main
ModuleNotFoundError: No module named 'conda_forge_ci_setup'
Tests failed for conda-forge-ci-setup-2.0.3-0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for conda-forge-ci-setup-2.0.3-0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
removing: conda-forge-ci-setup-2.0.3-0.tar.bz2
TESTS FAILED: conda-forge-ci-setup-2.0.3-0.tar.bz2
Exited with code 1
```

**Comment by CJ-Wright** [comment]
I'm not certain what is going on there.

**Comment by scopatz** [comment]
It doesn't seem to be running the pip install, or at least not in the correct directory.

**Comment by scopatz** [comment]
gonna try some fixes

**Comment by CJ-Wright** [comment]
I put in an echo it seems to be looking at the correct folder. I've also changed the pip install to the new syntax which is verbose.

**Comment by scopatz** [comment]
OK!

**Comment by CJ-Wright** [comment]
it seems that `branch2.0` is also failing on my local.

**Comment by CJ-Wright** [comment]
I got a non-feedstock version building https://travis-ci.org/CJ-Wright/conda-forge-ci-setup

**Comment by isuruf** [comment]
conda-forge-ci-setup is a major part of conda-forge and it should be bootstrappable, i.e., conda-forge-ci-setup should use itself to build and upload itself. Otherwise we'll be releasing a version that may have bugs

**Comment by CJ-Wright** [comment]
We *are* releasing a version which has bugs, so I don't know if bootstrap saved us. The code does consist of a library portion who most likely should be versioned and maintained separately from the feedstock. It would be nice to be able to have CI tests and all not wrapped up in the releasing of the code.

**Comment by jakirkham** [comment]
Based on the discussion here (haven't looked too deeply myself), it sounds like we are asking too much of `conda-forge-ci-setup`.

**Comment by CJ-Wright** [comment]
It might be nice to have the clobber file creation as part of the re-render. That way we can directly inspect the results.

**Comment by isuruf** [comment]
We discussed this somewhere. It needs to be at runtime. Otherwise you need a rerender after each build number change and forgetting that can be very confusing.

**Pull request merged**
