### PR TITLE
ENH make .conda the default

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forhe-admin rerender

**Comment by beckermr** [comment]
@conda-forge/core there have been no major breakages so we're ready to merge this one!

**Comment by jakirkham** [comment]
Thanks Matt! 🙏

**Comment by jakirkham** [comment]
Just a reminder feedstocks can opt-out as needed [using `conda-forge.yml` as noted in the docs]( https://conda-forge.org/docs/maintainer/conda_forge_yml.html#conda-build )

**Pull request merged**
