### PR TITLE
add cuda 11.2.1 and make it default for cuda 11.2 builds

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Review by kkraus14 — APPROVED** [review]
lgtm

**Comment by jaimergp** [comment]
Looks like 11.2.1 got stuck. Let's see if it was sporadic or something we need to fix. Retrying...

**Comment by jaimergp** [comment]
Now a download error on 11.1... I guess that's ok and no need to rerun?

**Comment by jaimergp** [comment]
I think this is ready for review/merge, @conda-forge/core!

**Comment by kkraus14** [comment]
> I think this is ready for review/merge, @conda-forge/core!

Trying to rerun the failing job and will merge once it passes, thanks!

**Comment by jaimergp** [comment]
Thanks! 🎉

**Pull request merged**
