### PR TITLE
Fix CUDA Windows installer urls

### PR DESCRIPTION
**Pull request by leofang**
cc: @jakirkham @h-vetinari for vis

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
Q: Should I bump the build or version number?

**Comment by jakirkham** [comment]
Thanks Leo! 🙏

Would bump the patch version

**Comment by leofang** [comment]
> Would bump the patch version

Thanks, John. Done.

**Comment by jakirkham** [comment]
Thank you both! 🙏

**Pull request merged**
