### PR TITLE
use conda-forge-metadata for feedstock-outputs

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Needs:
- https://github.com/regro/conda-forge-metadata/pull/7
- https://github.com/regro/conda-forge-metadata/issues/11

### CODE REVIEW

**Comment by jaimergp** [comment]
I am running into a bit of a bootstrapping problem (hence the edits in the scripts/workflows), but other than that this is ready for review @conda-forge/core!

**Review by beckermr — CHANGES_REQUESTED** [review]
I'm not sure the logic is the same. If we cannot find an output then we assume things are ok.

**Review by beckermr — APPROVED** [review]
Ohh ignore me I cannot read.

**Comment by beckermr** [comment]
Oh woops we needed to bump the version in the recipe.

**Comment by jaimergp** [comment]
> Oh woops we needed to bump the version in the recipe.

See https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/238

**Pull request merged**
