### PR TITLE
Fix the case where build number is sometimes a int.

### LINKED ISSUE #25: Incorrect detection of more than one build number
xref https://github.com/conda/conda-build/issues/3095

I'm posting this here too since I'm not sure where this should be fixed.

An easy workaround would be to ensure that build numbers are `int` here:

https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/cfee5c07bf0559bf36372174e71c41eeb207a169/recipe/conda_forge_ci_setup/build_utils.py#L123

but maybe it's better to fix this in conda-build.

### PR DESCRIPTION
**Pull request by hmaarrfk**
Fixes #25

If i bump the build number, this will conflict with #21 🐩 

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ocefpaf** [comment]
LGTM

**Comment by ocefpaf** [comment]
@isuruf this is critical to some split-packages. Do you mind taking a quick look?

**Comment by hmaarrfk** [comment]
Thanks!

**Comment by ocefpaf** [comment]
Thanks for this one and for #21 @hmaarrfk!

**Comment by hmaarrfk** [comment]
I think we need a version bump for this one to actually get uploaded.

**Pull request merged**
