### PR TITLE
MNT: rerender

### LINKED ISSUE #36: @conda-forge-admin, please rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #36.

Here's a checklist to do before merging.
- [x] Bump the build number if needed.

Fixes #36

### CODE REVIEW

**Comment by bgruening** [comment]
It seems that those errors https://travis-ci.org/conda-forge/biom-format-feedstock/jobs/474476318 are due to the fact that this package is not available for python 3.7. I still don't understand why only OSX is trying to load py37 environments. But this PR should not hurt.

**Comment by jakirkham** [comment]
Hmm...thought we were seeing this on other non-Python 3.7 builds too. Or is the macOS installer Python 3.7 now?

It doesn't appear to add Python 3.7 though. Think you need [these lines]( https://github.com/conda-forge/numpy-feedstock/blob/33ba79c1aa808525aab8151ed6d3ec6d4612b88d/conda-forge.yml#L3-L5 ) and then another re-render.

**Comment by nsoranzo** [comment]
> > Or is the macOS installer Python 3.7 now?
> 
> Seems to. This PR is failing because of the issue it is supposed to fix :)

@bgruening Maybe try to apply the suggestion in https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/37#issuecomment-451176158 .

**Comment by mariusvniekerk** [comment]
This is targeting the wrong branch

**Comment by mariusvniekerk** [comment]
given that we've now moved off of the old branch pretty much completely we can likely just merge that to master and apply this fix.

**Comment by jakirkham** [comment]
> This is targeting the wrong branch

Yeah, we need a way to specify a branch to target when asking the bot to do something.

xref: https://github.com/conda-forge/conda-forge-webservices/issues/240

**Comment by mariusvniekerk** [comment]
pr made to merge branch2.0 to master #38

**Comment by nsoranzo** [comment]
Close?

**Pull request closed without merging**
