### PR TITLE
Add CUDA 11.7

### PR DESCRIPTION
**Pull request by bdice**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Update to CUDA 11.7. Follows the example of #181. MD5 checksums are from https://developer.download.nvidia.com/compute/cuda/11.7.0/docs/sidebar/md5sum.txt.

### CODE REVIEW

**Comment by bdice** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
cc @jaimergp

**Review by jakirkham — APPROVED** [review]

**Comment by jaimergp** [comment]
LGTM!

**Comment by jakirkham** [comment]
Thanks Bradley for the PR and Jaime for reviewing! 🙏

**Pull request merged**
