### PR TITLE
Fix upload for build number clobberered recipes

### PR DESCRIPTION
**Pull request by mariusvniekerk**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@ocefpaf I think this may address the issue raised today.

**Comment by ocefpaf** [comment]
Thanks @mariusvniekerk and @CJ-Wright for looking into this!

**Comment by CJ-Wright** [comment]
@mariusvniekerk is this ready to go?

**Comment by mariusvniekerk** [comment]
Yep

**Pull request merged**
