### PR TITLE
Compiler switch

### PR DESCRIPTION
**Pull request by mariusvniekerk**
Part of the great compiler switch set of things (https://github.com/conda-forge/conda-smithy/pull/836, https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/92).  

Changes
* This moves the proposed `build_utils.py` to here so that we don't need to replace that file on all feedstocks.
* Bumps the version number to >=2.  Presently we explicitly install 1.x so rerenders would not grab this version yet.
* Switches the scripts into a real python package that can be installed to allow code reuse.

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
I guess this recipe is made to use itself to upload?

**Comment by mariusvniekerk** [comment]
@conda-forge/core ready for review

**Comment by ocefpaf** [comment]
I guess we are ready! Merging! Big thanks to Marius and all the reviewersame.

**Comment by mariusvniekerk** [comment]
Merged this to branch2.0

**Pull request merged**
