### PR TITLE
Allow CPU_COUNT to be set externally

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Allows the CPU_COUNT variable to be set manually as suggested in https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/53#issuecomment-484327013.

### CODE REVIEW

**Comment by chrisburr** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Should we do the same thing on Windows?

**Comment by jakirkham** [comment]
cc @stuarteberg

**Comment by chrisburr** [comment]
This is the line which would need to be changed:

https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/1d9f8d0ee821f2aba827d0bc529f181cad5239c9/recipe/run_conda_forge_build_setup_win.bat#L4

From a couple of minutes and trying things out in an online VM I haven't figured out how to conditionally set this in batch. If someone has a suggestion I'm happy to add it.

**Pull request merged**
