### PR TITLE
BUG append to scripts properly

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
@isuruf There were a few bugs from the cross-compile PRs related to appending to the activate scrips instead of overwriting them in the osx sdk scripts and the cross compiler scripts.

**Comment by isuruf** [comment]
Thanks. `BUILD` should be set in the the compiler activation script though.

**Comment by beckermr** [comment]
> BUILD should be set in the the compiler activation script though.

Why? 

We set HOST there to correspond to the host/target system, but BUILD corresponds to the system that code is running on. 

Also, I think setting BUILD in the compiler activation scripts is too late? `conda-build` appears to try and set BUILD much earlier IIUIC.

**Comment by beckermr** [comment]
See this PR for where conda build sets it: https://github.com/conda/conda-build/pull/3999

**Comment by isuruf** [comment]
> but BUILD corresponds to the system that code is running on.

Yes, but the `BUILD` should be something that a cross compiler should know how to target when `CC_FOR_BUILD` is used by autoconf.

**Comment by beckermr** [comment]
> Yes, but the BUILD should be something that a cross compiler should know how to target when CC_FOR_BUILD is used by autoconf.

I am totally lost on what this statement even means. I read and understood most of this: http://tinf2.vub.ac.be/~dvermeir/manuals/autobook/autobook-1.2/autobook_271.html. What I don't follow is how the BUILD env var set by conda relates to what autotools is doing. Maybe the reasoning here is by analogy?

**Comment by isuruf** [comment]
Because people use it like `./configure --build=$BUILD --host=$HOST` etc.

**Comment by beckermr** [comment]
Right. So if you look at the conda-build PR I linked above, it appears that currently, conda-build is setting this itself. I guess you are saying we should deprecate that behavior?

**Comment by beckermr** [comment]
This one is ready to merge @isuruf!

**Pull request merged**
