### PR TITLE
Add cuda 11.2

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Todo:

- [x] Blocked by https://github.com/conda-forge/docker-images/pull/171

### CODE REVIEW

**Comment by jaimergp** [comment]
Docker images and `cudatoolkit` packages should be available now. Retrying CI!

**Comment by jaimergp** [comment]
Looks like there were some upload errors for cudatoolkit on that merge. Will try again tomorrow.

**Comment by jakirkham** [comment]
Packages should be out now. Restarted CI

**Review by jakirkham — APPROVED** [review]

**Comment by jaimergp** [comment]
Thanks @jakirkham !

**Pull request merged**
