### PR TITLE
Remove msmpi in System32 as well

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

cc @leofang

### CODE REVIEW

**Review by beckermr — APPROVED** [review]

**Review by leofang — APPROVED** [review]
LGTM. Thank you, @isuruf! This is much more robust than https://github.com/conda-forge/msmpi-feedstock/pull/11. I'll fix `msmpi` later.

**Review by leofang — COMMENTED** [review]
On a second thought: Can we also get this line migrated to here as well?
https://github.com/conda-forge/msmpi-feedstock/blob/7fc2c26641837eb233879473ca3ee0dd27242edb/recipe/activate.bat#L10
Together this PR will do a clean removal of MS-MPI in the Windows image.

**Comment by isuruf** [comment]
That's not an issue with running software. Only the DLLs in `C:\Windows\System32` are problematic. There's 100s of different software in azure that we can't possibly delete.

**Comment by leofang** [comment]
The uninstaller would also clean up the registry, among other actions, to force MS-MPI to look for the correct place at runtime.

**Comment by isuruf** [comment]
You mean finding smpd.exe? Looking at source code, it finds `smpd.exe` besides `msmpi.dll` first, which is the case for now. Also https://github.com/conda-forge/msmpi-feedstock/blob/master/recipe/activate.bat#L30 needs to be fixed because `LIBRARY_BIN` is not set outside of conda-build.

**Comment by leofang** [comment]
Not just smpd. One of the registry keys (MSPMSProvider) points to the dll, and the key is used at initializing the communication service if you are interested in the source. Also, the pretense of the registry keys would prevent the installer from doing the right job (installing to a custom path). I'd rather keep things simple by just removing everything, which is really only one more line to add.

**Comment by isuruf** [comment]
I'd like to keep the maintenance burden lower. After merging this PR, if you run into an issue, we can re-evaluate.

**Comment by isuruf** [comment]
Can you open an issue in this feedstock to track this?

**Pull request merged**
