### PR TITLE
Remove cdt_name usage now that cdt_name == conda

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
I don't know enough about the CUDA requirements to properly review this PR. Hopefully someone else can double check.

**Review by h-vetinari — APPROVED** [review]
PR looks fine, but we need a patch version bump

**Comment by h-vetinari** [comment]
(came looking for this because things broke in https://github.com/conda-forge/libhwloc-feedstock/pull/83)

There's way more clean-ups possible (some discussion on this in https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/363), but for now we should quickly merge this to unblock recipes that cross-compile cuda.

**Comment by h-vetinari** [comment]
This broke a couple other feedstocks too (e.g. arrow), so let's merge this and do any other relevant clean-ups in #363 (or another PR)

**Pull request merged**
