### PR TITLE
BUG make sure to use only allowed dist names

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
cc @isuruf

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by isuruf** [comment]
This should only be done if there's `test_downstreams` text in `recipe/meta.yaml`. Saves a lot of time in CI and crucial for builds near the travis time limit.

**Comment by isuruf** [comment]
Great. Thanks.

**Pull request merged**
